aws_instances_poller_settings:
    region: us-east-1
    expose_tags: ['Name', 'team', 'Owner', 'Laboratory']
    max_chunk_size: 50

aws_spot_prices_poller_settings:
    region: us-east-1
    #availability_zones: [ 'us-east-1a' ]
    #instance_types: [ 'm3.xlarge' ]
    products: [ 'Linux/UNIX', 'Windows', 'Linux/UNIX (Amazon VPC)', 'Windows (Amazon VPC)' ]
    max_chunk_size: 200

scrape_settings:
    listen_on: 0.0.0.0:8082
    read_timeout: 10
    keep_alive_timeout: 60
    polling_period: 60
